import mongoose from "mongoose";
const orderSchema=new mongoose.Schema({ 
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,                                   
             required:true    
        },
        country:{
            type:String,
            required:true
        },
        zipCode:{
            type:String,
            required:true
        },
    },
    orderItems:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            product:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"Product",
                required:true
            }
        }
    ],
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true
        }
    },
    taxPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    shippingPrice:{
        type:Number,
        required:true,
        default:0.0 
    },
    orderstatus:{
        type:String,
        required:true,
        default:"Processing"
    },
        paidAt:{
            type:Date,
            required:true
        },
        totalPrice:{
            type:Number,
            required:true,
            default:0.0
        }
    }, { timestamps: true })

export const Order=mongoose.model("Order",orderSchema);     